/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demolib;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {

    @Test
    void isPositiveNumber() {
        String strPositive = "1.21";
        String strNegative = "-8";
        String strString = "dsf";
        assertTrue(StringUtils.isPositiveNumber(strPositive));
        assertFalse(StringUtils.isPositiveNumber(strNegative));
        assertFalse(StringUtils.isPositiveNumber(strString));


    }
}
