/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demolib;

import static org.apache.commons.lang3.math.NumberUtils.isParsable;

public class StringUtils {
        public static boolean isPositiveNumber(String str) {
        if (isParsable(str)) {
            double number = Double.parseDouble(str);
            return number > 0;
        }
        return false;
    }
}
